// ═══════════════════════════════════════════
// SUSTAINA — AI Sustainability Reports Page
// Monthly reports generation, PDF print, and PNG card sharing
// ═══════════════════════════════════════════

import { 
  getProfile, 
  getActivities, 
  getGoals, 
  getMemory,
  logTimelineEvent 
} from '../state/store.js';
import { getAIReport } from '../services/gemini.js';
import { fetchSimulations, fetchPurchaseHistory } from '../services/supabase.js';
import { icons } from '../components/icons.js';

let activePeriod = 'May 2026';
let generatedReport = null;
let isGenerating = false;

const PERIODS = ['May 2026', 'April 2026', 'March 2026', 'February 2026'];

export function renderReports(container) {
  renderReportsPage(container);
}

function renderReportsPage(container) {
  container.innerHTML = `
    <!-- Print Styling -->
    <style id="reports-print-style">
      @media print {
        #sidebar-container, #topbar-container, .no-print, button, select {
          display: none !important;
        }
        #main-content {
          margin-left: 0 !important;
        }
        #page-content {
          padding: 0 !important;
        }
        .report-print-container {
          background: white !important;
          color: black !important;
          border: none !important;
          box-shadow: none !important;
          width: 100% !important;
          padding: 0 !important;
        }
      }
    </style>

    <div class="page-enter">
      <div class="page-header no-print">
        <div>
          <h1 class="page-title">AI Sustainability Reports</h1>
          <p class="page-subtitle">Compile and review detailed carbon footprint audits generated by Arya.</p>
        </div>
        <div style="display: flex; gap: var(--space-3); align-items: center;">
          <label for="report-period-select" class="text-xs text-secondary font-semibold" style="display: inline-block; cursor: pointer;">Select Period:</label>
          <select id="report-period-select" style="max-width: 160px;">
            ${PERIODS.map(p => `
              <option value="${p}" ${p === activePeriod ? 'selected' : ''}>${p}</option>
            `).join('')}
          </select>
          <button class="btn btn-primary" id="btn-generate-report">
            Generate Report
          </button>
        </div>
      </div>

      <!-- Report Content Card -->
      <div id="report-output-area" class="report-print-container">
        ${renderReportBody()}
      </div>
    </div>
  `;

  // Attach event handlers
  document.getElementById('report-period-select').addEventListener('change', (e) => {
    activePeriod = e.target.value;
    generatedReport = null;
    renderReportsPage(container);
  });

  document.getElementById('btn-generate-report').addEventListener('click', () => {
    generateReportAction(container);
  });

  // Attach report actions (PDF/PNG) if report is active
  if (generatedReport) {
    document.getElementById('btn-pdf-export')?.addEventListener('click', () => {
      window.print();
    });

    document.getElementById('btn-png-export')?.addEventListener('click', () => {
      exportPNGCard(getProfile(), generatedReport);
    });
  }
}

function renderReportBody() {
  if (isGenerating) {
    return `
      <div class="card text-center" style="padding: var(--space-16) 0;">
        <div style="font-size: 44px; margin-bottom: var(--space-4); animation: spin 1s linear infinite;">🍃</div>
        <h3 style="font-family: var(--font-heading); font-weight: 700; margin-bottom: var(--space-2);">Arya is compiling your report...</h3>
        <p class="text-xs text-secondary">Analyzing activities, goals, and twins calculations for ${activePeriod}.</p>
      </div>
    `;
  }

  if (!generatedReport) {
    return `
      <div class="card text-center" style="padding: var(--space-12) 0;">
        <div style="font-size: 64px; margin-bottom: var(--space-4); filter: grayscale(1);">📋</div>
        <h3 style="font-family: var(--font-heading); font-weight: 700; margin-bottom: var(--space-2);">Report is ready to compile</h3>
        <p class="text-xs text-secondary mb-6">Click 'Generate Report' to trigger Gemini Flash audit report for ${activePeriod}.</p>
      </div>
    `;
  }

  const r = generatedReport;
  return `
    <div class="card stagger-1" style="padding: var(--space-8); display: flex; flex-direction: column; gap: var(--space-6);">
      
      <!-- Report Header -->
      <div style="display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 1px solid var(--border-light); padding-bottom: var(--space-4);">
        <div>
          <div style="font-size: var(--text-xs); color: var(--green-700); font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px;">Monthly Sustainability Audit</div>
          <h2 style="font-family: var(--font-heading); font-size: var(--text-2xl); font-weight: 800; color: var(--green-800); margin-top: var(--space-1);">${activePeriod}</h2>
        </div>
        <div class="no-print" style="display: flex; gap: var(--space-2);">
          <button class="btn btn-secondary btn-sm" id="btn-pdf-export" style="padding: var(--space-2) var(--space-4);">
            Export PDF
          </button>
          <button class="btn btn-primary btn-sm" id="btn-png-export" style="padding: var(--space-2) var(--space-4);">
            Share Summary Card
          </button>
        </div>
      </div>

      <!-- Report Columns Grid -->
      <div class="grid-2" style="gap: var(--space-6);">
        <!-- Column 1 -->
        <div style="display: flex; flex-direction: column; gap: var(--space-5);">
          <!-- Summary -->
          <div>
            <h4 style="font-family: var(--font-heading); font-weight: 700; font-size: var(--text-md); color: var(--green-800); margin-bottom: var(--space-2);">Executive Summary</h4>
            <p style="font-size: var(--text-sm); color: var(--text-primary); line-height: var(--leading-relaxed); text-align: left;">${r.summary}</p>
          </div>
          <!-- Achievements & Savings -->
          <div class="grid-2" style="gap: var(--space-4);">
            <div class="card" style="background: var(--green-50); border: 1px solid var(--green-100); padding: var(--space-4);">
              <div class="text-xs text-secondary font-semibold">Savings Recorded</div>
              <div style="font-family: var(--font-heading); font-size: var(--text-md); font-weight: 700; color: var(--green-800); margin-top: var(--space-1);">${r.savings}</div>
            </div>
            <div class="card" style="background: #e3f0ff; border: 1px solid #cce3ff; padding: var(--space-4);">
              <div class="text-xs text-secondary font-semibold">Achievements</div>
              <div style="font-family: var(--font-heading); font-size: var(--text-md); font-weight: 700; color: #1a5fb4; margin-top: var(--space-1);">${r.achievements}</div>
            </div>
          </div>
          <!-- Carbon Twin Progress -->
          <div>
            <h4 style="font-family: var(--font-heading); font-weight: 700; font-size: var(--text-md); color: var(--green-800); margin-bottom: var(--space-2);">Carbon Twin Alignment</h4>
            <p style="font-size: var(--text-sm); color: var(--text-secondary); line-height: var(--leading-relaxed); text-align: left;">${r.carbonTwinProgress}</p>
          </div>
        </div>

        <!-- Column 2 -->
        <div style="display: flex; flex-direction: column; gap: var(--space-5);">
          <!-- Emission breakdown & Top Impact -->
          <div>
            <h4 style="font-family: var(--font-heading); font-weight: 700; font-size: var(--text-md); color: var(--green-800); margin-bottom: var(--space-2);">Emission Breakdown</h4>
            <p style="font-size: var(--text-sm); color: var(--text-secondary); line-height: var(--leading-relaxed); text-align: left; margin-bottom: var(--space-3);">${r.emissionBreakdown}</p>
            <div class="card" style="padding: var(--space-4); background: var(--neutral-50);">
              <div class="text-xs text-secondary font-semibold">Primary Emission Driver</div>
              <div style="font-family: var(--font-heading); font-size: var(--text-md); font-weight: 700; color: var(--accent-red); margin-top: var(--space-1);">${r.topImpactSource}</div>
            </div>
          </div>

          <!-- Recommendations -->
          <div>
            <h4 style="font-family: var(--font-heading); font-weight: 700; font-size: var(--text-md); color: var(--green-800); margin-bottom: var(--space-2);">Arya's Targeted Recommendations</h4>
            <div style="display: flex; flex-direction: column; gap: var(--space-2);">
              ${r.recommendations.map(rec => `
                <div style="display: flex; gap: var(--space-2); font-size: var(--text-sm); align-items: flex-start; text-align: left;">
                  <span style="color: var(--green-600); font-weight: bold; margin-top: 1px;">•</span>
                  <span>${rec}</span>
                </div>
              `).join('')}
            </div>
          </div>

          <!-- Next Month Plan -->
          <div style="border-top: 1px solid var(--border-light); padding-top: var(--space-4);">
            <h4 style="font-family: var(--font-heading); font-weight: 700; font-size: var(--text-md); color: var(--green-800); margin-bottom: var(--space-2);">Strategy for Next Month</h4>
            <p style="font-size: var(--text-sm); color: var(--text-secondary); line-height: var(--leading-relaxed); text-align: left;">${r.nextMonthPlan}</p>
          </div>
        </div>
      </div>
      
      <!-- Footer -->
      <div style="border-top: 1px solid var(--border-light); padding-top: var(--space-4); display: flex; justify-content: space-between; align-items: center; font-size: var(--text-xs); color: var(--text-tertiary);">
        <span>Sustaina AI Engine v3.0</span>
        <span>Generated via Arya Pulse™ Voice Assistant</span>
      </div>
    </div>
  `;
}

async function generateReportAction(container) {
  isGenerating = true;
  renderReportsPage(container);

  const profile = getProfile();
  const activities = getActivities();
  const goals = getGoals();
  const memory = getMemory();

  // Fetch Supabase historical tables for AI context
  const simulations = await fetchSimulations(profile.id || '');
  const purchases = await fetchPurchaseHistory(profile.id || '');

  try {
    const report = await getAIReport(
      'monthly',
      activePeriod,
      activities,
      goals,
      memory,
      simulations,
      purchases
    );

    generatedReport = {
      ...report,
      period: activePeriod
    };

    // Log timeline event
    logTimelineEvent({
      type: 'report_generated',
      title: 'Monthly AI Report Generated',
      description: `Gemini compiled carbon footprints audit report for ${activePeriod}.`,
      icon: '📋'
    });

  } catch (e) {
    console.error('Failed to generate AI report:', e);
  } finally {
    isGenerating = false;
    renderReportsPage(container);
  }
}

function exportPNGCard(profile, reportData) {
  const canvas = document.createElement('canvas');
  canvas.width = 800;
  canvas.height = 450;
  const ctx = canvas.getContext('2d');

  // Gradient background
  const grad = ctx.createLinearGradient(0, 0, 800, 450);
  grad.addColorStop(0, '#1a3409'); // Forest green-900
  grad.addColorStop(1, '#2d5016'); // Forest green-800
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, 800, 450);

  // Decorative circles
  ctx.fillStyle = 'rgba(255, 255, 255, 0.03)';
  ctx.beginPath();
  ctx.arc(800, 0, 300, 0, Math.PI * 2);
  ctx.fill();
  ctx.beginPath();
  ctx.arc(0, 450, 200, 0, Math.PI * 2);
  ctx.fill();

  // Draw Brand Logo
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 24px Manrope, sans-serif';
  ctx.fillText('🌱 Sustaina', 50, 60);

  ctx.fillStyle = 'rgba(255,255,255,0.7)';
  ctx.font = '14px Inter, sans-serif';
  ctx.fillText('MY MONTHLY SUSTAINABILITY REPORT', 50, 95);

  // User Name
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 36px Manrope, sans-serif';
  ctx.fillText(profile.name || 'Aryan Medigeri', 50, 140);

  ctx.fillStyle = 'rgba(255,255,255,0.8)';
  ctx.font = '14px Inter, sans-serif';
  ctx.fillText(`Period: ${reportData.period || 'May 2026'}`, 50, 175);

  // Dividers
  ctx.strokeStyle = 'rgba(255,255,255,0.15)';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(50, 210);
  ctx.lineTo(750, 210);
  ctx.stroke();

  // Metrics Columns
  // Col 1: CO2 Saved
  ctx.fillStyle = 'rgba(255,255,255,0.7)';
  ctx.font = '13px Inter, sans-serif';
  ctx.fillText('CARBON AVOIDED', 50, 250);

  ctx.fillStyle = '#b5dd9a'; // green-200
  ctx.font = 'bold 44px Manrope, sans-serif';
  
  // Calculate CO2 Saved
  const totalCO2 = parseFloat(profile.electricityUnits ? (profile.electricityUnits * 0.8).toFixed(1) : '12.5');
  ctx.fillText(`${totalCO2} kg`, 50, 305);

  // Col 2: Money Saved
  ctx.fillStyle = 'rgba(255,255,255,0.7)';
  ctx.font = '13px Inter, sans-serif';
  ctx.fillText('MONEY SAVED', 300, 250);

  ctx.fillStyle = '#fef3d0'; // Gold light
  ctx.font = 'bold 44px Manrope, sans-serif';
  ctx.fillText(`₹${Math.round(totalCO2 * 5.2)}`, 300, 305);

  // Col 3: Trees Equivalent
  ctx.fillStyle = 'rgba(255,255,255,0.7)';
  ctx.font = '13px Inter, sans-serif';
  ctx.fillText('TREES EQUIVALENT', 550, 250);

  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 44px Manrope, sans-serif';
  ctx.fillText(`${Math.round(totalCO2 / 21)}`, 550, 305);

  // Footer Tagline
  ctx.fillStyle = 'rgba(255,255,255,0.5)';
  ctx.font = '12px Inter, sans-serif';
  ctx.fillText('Generated via Arya Pulse™ AI Companion', 50, 390);

  // Trigger Download
  const link = document.createElement('a');
  link.download = `sustaina_${reportData.period.replace(' ', '_')}_report_card.png`;
  link.href = canvas.toDataURL('image/png');
  link.click();
}
